@startuml

!pragma layout smetana

class Login{

    string correoElectronico
    string contraseña

}

class Principal{

    barra principal
    textbox Información_empresa
    bottom Desplegable_Ubicación
    textbox Información_ubicación



}

class Servicios{

    barra mantenimiento
    barra instalación
    barra reparación
    bottom contratarServicio
    hipervinculo Whatsapp
}

Class Productos{

    list productos
    bottom Carrito
    bottom Comprar
    float total

}


Login *-- Principal
Principal o-- Servicios
Principal o-- Productos

@enduml