@startuml

    /' Actor '/
actor Usuario as Usuario

boundary "Fe pantalla de login" as pantallaLogin
boundary "Fe mostrar Error de registro" as errorLogin
boundary "Iniciar" as iniciar

    /' Casos de uso '/
usecase (Login) as login
usecase (Pantalla Principal) as principal
    /' Control '/
control "BE Obtener Usuarios Registrados" as obtenerusuario
control "Iniciar" as iniciarlogin

    /' Entity '/
entity "Obtener base de datos de usuarios" as baseUsuarios


Usuario -> login
login -> pantallaLogin
pantallaLogin -down-> obtenerusuario
obtenerusuario -right-> baseUsuarios
obtenerusuario -left-> errorLogin : Mostrar error
obtenerusuario -up-> iniciarlogin: Validar
iniciarlogin -left-> iniciar 
iniciar -left-> principal

@enduml